# Notea Configuration File (Compatibility version)
# ------------------------------------------------
# NOTE: Environment variables override file configuration values in most cases

# Authentication configuration
auth:
    # Type of configuration
    #   none: No authentication, anyone can view/edit (same as DISABLE_PASSWORD)
    #   basic: Basic authentication; a password.
    type: basic
    # PLANNED: Multiple users and usernames
    password: 123

# Store configuration
store:
    # type is unused for now
    type: s3
    # endpoint is the same as STORE_END_POINT; must be specified if env doesn't
    endpoint: http://localhost:9000
    # accessKey is the same as STORE_ACCESS_KEY; must be specified if env doesn't
    accessKey: YOUR_ACCESS_KEY
    # secretKey is the same as STORE_SECRET_KEY; must be specified if env doesn't
    secretKey: YOUR_SECRET_KEY
    # bucket is the same as STORE_BUCKET; defaults to "notea"
    bucket: notea
    # forcePathStyle is the same as STORE_FORCE_PATH_STYLE; defaults to false
    forcePathStyle: true
    # proxyAttachments is the same as DIRECT_RESPONSE_ATTACHMENT; defaults to false
    proxyAttachments: true

# Server configuration
server:
    # useSecureConfig is the same as COOKIE_SECURE; if in production (which is for end-users), it will be true, else it'll be false
    useSecureConfig: true
    # baseUrl is the same as BASE_URL; not required
    baseUrl: https://example.com