name: Publish to Docker Hub

on:
    push:
        branches:
            - 'main'
            - 'release'
        tags:
            - v**
    pull_request:
        types:
            - opened
            - reopened

jobs:
    # test:
    #   name: Test
    #   runs-on: ubuntu-latest
    #   steps:
    #     - uses: actions/checkout@v2
    #     - name: Install modules
    #       run: yarn
    #     - name: Run MinIO
    #       run: docker-compose up -d
    #     - name: Run tests
    #       run: yarn test
    publish:
        name: Publish
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master
            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v4
              with:
                  images: cinwell/notea
                  tags: |
                      type=ref,event=branch
                      type=ref,event=pr
                      type=semver,pattern={{version}}
                      type=semver,pattern={{major}}.{{minor}}
                      type=edge,branch=main
            - uses: mstachniuk/ci-skip@v1
              with:
                  fail-fast: true
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                  context: .
                  platforms: linux/amd64,linux/arm64
                  network: host
                  push: ${{ github.event_name != 'pull_request' }}
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
